// REINICIE A APLICAÇÃO
// CRIE UM USUÁRIO
POST http://localhost:3000/auth/register
Content-Type: application/json

{
	"name": "Genoveva",
	"email": "genoveva@email.com",
	"password": "12345+A"
}
###

// LOG COM UM USER 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "genoveva@email.com",
	"password": "12345+A"
}
###

//COM TOKEN INVALIDO
GET http://localhost:3000/users
Authorization: Barer qualquercoisaqui
###

//COM TOKEN DE USER
//COPIE O TOKEN RECEBIDO
GET http://localhost:3000/users
Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMTg5YmY0LWU0NzktNDY3NC04NWE4LTJiZGMzZTM2ZTkwYyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUxOTM1NDM4LCJleHAiOjE3NTE5MzkwMzh9._KheLplaAyY7nYD104BPoJQXWpeJ6jmMe-3SL4feuSM
###

//LOGIN COM ADMIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "elesbao@email.com",
	"password": "123456"
}
###

//COM TOKEN DE AMIN
//COPIE O TOKEN RECEBIDO
GET http://localhost:3000/users
Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MDc1ZTJkLTRmYjQtNGE3Zi04ZGRkLTFiMWFiOWI4NGQzZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTkzNTQ1MiwiZXhwIjoxNzUxOTM5MDUyfQ.tEQSD7cW3mjUBPCGUQL4UU1HfL8TZMcE3X39_8I9X18
###

// CRIE TESTES PARA AS DEMAIS ROTAS

// GET USER
GET http://localhost:3000/users/10189bf4-e479-4674-85a8-2bdc3e36e90c
Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MDc1ZTJkLTRmYjQtNGE3Zi04ZGRkLTFiMWFiOWI4NGQzZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTkzNTQ1MiwiZXhwIjoxNzUxOTM5MDUyfQ.tEQSD7cW3mjUBPCGUQL4UU1HfL8TZMcE3X39_8I9X18
###

// ALTERAR USER
PUT http://localhost:3000/users/10189bf4-e479-4674-85a8-2bdc3e36e90c
Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MDc1ZTJkLTRmYjQtNGE3Zi04ZGRkLTFiMWFiOWI4NGQzZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTkzNTQ1MiwiZXhwIjoxNzUxOTM5MDUyfQ.tEQSD7cW3mjUBPCGUQL4UU1HfL8TZMcE3X39_8I9X18
Content-Type: application/json

{
   "name": "Genoveva Alterada"
}
###

// DELETAR USER
DELETE http://localhost:3000/users/10189bf4-e479-4674-85a8-2bdc3e36e90c
Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5MDc1ZTJkLTRmYjQtNGE3Zi04ZGRkLTFiMWFiOWI4NGQzZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTkzNTQ1MiwiZXhwIjoxNzUxOTM5MDUyfQ.tEQSD7cW3mjUBPCGUQL4UU1HfL8TZMcE3X39_8I9X18
###